# Generated by Django 4.0.2 on 2022-02-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
