# Generated by Django 4.0.2 on 2022-02-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
